### PR TITLE
Fully fledged implementation of instance wrapper

### PR DESCRIPTION
**Pull request by SilentsReplacement**
Fully fledged implementation of instance wrapper with heavy code refactor and more features. Example use case:

```lua
local testInstance = Utility.osm.make("Part", {
	Transparency = 1,
	Parent = workspace,
	BrickColor = BrickColor.Random(),
	Attributes = {
		IsNoob = true
	},
	CollectionTags = {
		e = "OINK"
	},

	Children = {
		bos = Utility.osm.make("Part", {
			Transparency = 1
		}),

		e = Utility.osm.make("Model", {

		})
	}
})

testInstance:SetAttribute("IsNoob23", nil)
testInstance:SetCollectionTag("236262", "o")
```

### CODE REVIEW

**Comment by SilentsReplacement** [comment]
Also allows you to dynamically set attributes and collection tags, access Children and work with them easily and also set attributes / collection tags while creating the instance. Each instance created and returned also has a `Instance` member.

**Comment by 7kayoh** [comment]
Changed base to staging, please use staging from now on.

**Review by 7kayoh — APPROVED** [review]
Approved, will be adjusted to fit the system

**Comment by 7kayoh** [comment]
Note that CollectionService's tagging system does only allow the tag name, you can not put a value inside a tag.

**Comment by SilentsReplacement** [comment]
> Changed base to staging, please use staging from now on.

Ok, got it.

**Pull request merged**
